CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (user_id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests (
                                        request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        description VARCHAR(2000) NOT NULL,
                                        requestor_id INTEGER,
                                        CONSTRAINT pk_request PRIMARY KEY (request_id),
                                        CONSTRAINT "requests_users_id_fk"
                                            FOREIGN KEY (requestor_id) REFERENCES users ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS items (
                                     item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(2000) NOT NULL,
                                     available BOOLEAN NOT NULL ,
                                     owner_id INTEGER,
                                     request_id INTEGER,
                                     CONSTRAINT pk_item PRIMARY KEY (item_id),
                                     CONSTRAINT "items_users_id_fk"
                                         FOREIGN KEY (owner_id) REFERENCES users ON DELETE CASCADE,
                                     CONSTRAINT "items_requests_id_fk"
                                         FOREIGN KEY (request_id) REFERENCES requests ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS bookings (
                                        booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL ,
                                        end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id INTEGER NOT NULL ,
                                        booker_id INTEGER NOT NULL ,
                                        status VARCHAR(25),
                                        CONSTRAINT pk_booking PRIMARY KEY (booking_id),
                                        CONSTRAINT "bookings_items_id_fk"
                                            FOREIGN KEY (item_id) REFERENCES items ON DELETE CASCADE,
                                        CONSTRAINT "bookings_users_id_fk"
                                            FOREIGN KEY (booker_id) REFERENCES users ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS comments (
                                        comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        text VARCHAR(1000) NOT NULL,
                                        item_id INTEGER NOT NULL ,
                                        author_id INTEGER NOT NULL ,
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        CONSTRAINT pk_comment PRIMARY KEY (comment_id),
                                        CONSTRAINT "comments_items_id_fk"
                                            FOREIGN KEY (item_id) REFERENCES items ON DELETE CASCADE,
                                        CONSTRAINT "comments_users_id_fk"
                                            FOREIGN KEY (author_id) REFERENCES users ON DELETE CASCADE
);